## Numpy

In [4]:

import numpy as np
rng = np.random.default_rng()
a = rng.integers(-10,11, 10000)


### Zadanie 1.

Stwórz losową tablicę 10,000 liczb, następnie do każdego elementu dodaj 1. Następnie napisz dokładnie tę samą funkcję używając `numpy` i jego tablic. Porównaj czas działania swoich rozwiązań.

In [16]:
import random
t = [random.randint(-10,10) for _ in range(10000)]
t = [x+1 for x in t]


### Zadanie 2.

Napisz funkcje obliczajaca $\sin(x) + \cos(x)$ dla kazdego elementu tablicy 10,000 losowych liczb używając pętli oraz używając numpy, porownaj ich szybkość podobnie jak w poprzednim zadaniu.

In [5]:
from math import sin, cos
import random
data = [ random.uniform(0,10) for _ in range(10000) ]
numpy_data = np.array(data)
def trig(data):
    return [sin(val) + cos(val) for val in data]    
def nptrig(npiter):
    return np.sin(npiter) +np.cos(npiter)

def x():
    t = np.random.uniform(1,10,10000)
    return np.sin(t) + np.cos(t)
print('klasyczne:')
%timeit trig(data)
print('numpy:')
%timeit x()

klasyczne:
1.3 ms ± 21.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
numpy:
382 μs ± 23.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Zadanie 3.

Napisz wydajniejszą forme następujących funkcji. Dopisz do każdej test potwierdzający szybkość zaproponowanego rozwiązania.

In [91]:
def cube_sum(x):
    """Zwraca sume szescianow elementow"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result

def np_cube_sum(x):
    return np.sum(x**3)

def np_almost_variance(x):
    return np.mean((x - np.mean(x))**4)


data = [ random.uniform(0,10) for _ in range(10000) ]
npdata = np.random.uniform(1,10,10000)
print('klasycznie:')
%timeit almost_variance(data)
print('numpy:')
%timeit np_almost_variance(npdata)


klasycznie:
1.39 ms ± 86.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
numpy:
270 μs ± 20 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Zadanie 4.

Wykorzystujac `broadcasting` (patrz na rysunek poniżej) stwórz tabliczkę mnożenia tzn. tablice $A$ taka, ze $$A_{ij} = i \cdot j\;\;\;\;\; \forall i,j \in \{1,\dots,10\}$$

Czy potrafisz wykonać to jednym poleceniem, nie używajac przy tym petli/comprehensions?

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [6]:
x = np.arange(1,11).reshape((10,1)) * np.arange(1,11)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Zad 5.

Wygeneruj losową tablice `10 x 5`, która będzie reprezentować `10` punktów w `5` wymiarowej przestrzeni. Napisz funkcje, która policzy odleglość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to **bez użycia żadnych pętli/comprehensions**? 

Przypomnienie, dla dwóch wektorów: $x$ i $y$ $$d_{e}(x,y) = \| x - y \|^2_2 = \sum_{i=1}^d (x_i - y_i)^2 $$

In [8]:


def euklides(row=10, col=5):
    
    matrix = np.random.uniform(1,2, size =(row,col))

    new1 , new2 = matrix[:,np.newaxis,:], matrix[np.newaxis,:,:]

    diffs = new1 - new2

    sq = diffs**2

    sumy = np.sum(sq,axis=-1)

    return np.sqrt(sumy)

a = euklides()        
print(a)

[[0.         0.55367377 0.90356124 0.40173683 0.71561596 1.19781318
  1.02294871 0.92856604 0.96816931 1.16189803]
 [0.55367377 0.         0.90148588 0.61425896 0.92403752 1.00323283
  0.62737794 1.03199771 1.05887805 0.96189444]
 [0.90356124 0.90148588 0.         0.81318007 0.6848814  1.00122747
  0.96329988 1.22075171 1.16860464 0.56848312]
 [0.40173683 0.61425896 0.81318007 0.         0.87531219 1.08863822
  1.00939165 0.83893604 0.98841309 1.11802654]
 [0.71561596 0.92403752 0.6848814  0.87531219 0.         1.12907587
  1.09632796 1.06456035 0.90538875 0.82633257]
 [1.19781318 1.00323283 1.00122747 1.08863822 1.12907587 0.
  0.56240798 0.76303436 0.68900436 0.70472716]
 [1.02294871 0.62737794 0.96329988 1.00939165 1.09632796 0.56240798
  0.         1.0182716  0.94838934 0.70106481]
 [0.92856604 1.03199771 1.22075171 0.83893604 1.06456035 0.76303436
  1.0182716  0.         0.36168353 1.19868681]
 [0.96816931 1.05887805 1.16860464 0.98841309 0.90538875 0.68900436
  0.94838934 0.36168

### Zad 6.

Napisz funkcje do "wybielania" zbioru punktow, tj. aplikowania następującej transformacji (ponownie, zrób to bez użycia pętli etc.)
$$
\mathrm{white}(X)_{ij} = \frac{X_{ij} - \mu_j}{\sigma_j}
$$
gdzie $\mu_j$ to srednia po $j$ej kolumnie, a $\sigma_j$ to odchylenie standardowe po tej kolumnie, np.

$$
\mathrm{white}\left ( \left [ \begin{matrix} 
0& 1\\
2& 3\\
4& 5\\
6& 7\\
8& 9
\end{matrix} \right ] \right ) = 
\left [ \begin{matrix} 
-1.41421356& -1.41421356\\
-0.70710678& -0.70710678\\
0.        &  0.        \\
0.70710678&  0.70710678\\
1.41421356&  1.41421356
\end{matrix} \right ]
$$


W szczególności średnia po poszczególnych kolumnach nowej macierzy powinna wynosić `0` a odchylenie standardowe `1`.

In [9]:
def wybielanie(A):
    mean = np.mean(A,axis=0)
    std = np.std(A, axis=0)
    B = (A - mean)/std
    return (B, np.mean(B, axis=0), np.std(B, axis=0))
print(wybielanie(np.random.normal(size=(10,2))))


(array([[-0.20000727,  1.65919311],
       [ 1.83030462,  0.09439597],
       [ 0.04967692, -0.16167816],
       [-0.86131869,  0.09444243],
       [-2.06276345,  0.79189504],
       [-0.0965216 , -0.75265894],
       [ 0.04517542,  1.37199898],
       [ 0.94319398, -0.43448745],
       [-0.3929199 , -0.88866157],
       [ 0.74517996, -1.77443941]]), array([3.33066907e-17, 0.00000000e+00]), array([1., 1.]))


### Zad 7.

Majac dana tablice dowolnie wymiarowa (dla uproszczenia mozesz przyjac ze jedno lub dwu) oraz liczbe `x` znajdz najblizsza wartosc `x` w `A`, tzn. 

$$
\mathrm{closest}(x, A) = \arg\min_{a\in A}| x - a| 
$$

np. 

$$
\mathrm{closest}(1.5, [1, -4, 3]) = 1
$$

Ponownie, czy potrafisz zrobic to bez petli, etc.?


In [11]:
def closest(A,x):
    diff = np.sum(np.abs(A - x) , axis=0)
    id = np.argmin(diff)
    return A[id]

closest(np.random.uniform(size=(10,10)), np.zeros(10))


array([0.52864214, 0.08751484, 0.2110839 , 0.07603218, 0.9991266 ,
       0.48580042, 0.54633674, 0.78354443, 0.05815838, 0.83237711])

### Zad 8.

Zaimplementuj proste liczenie wartosci wielomianu o zadanych wspolczynnikach (analogie `np.poly1d`), czyli funkcje

$$
\mathrm{poly}(x, a) = a_0 + a_1 x + a_2 x^2 + \dots + a_k x^k = \sum_{i=1}^k a_i x^i
$$

Czy potrafisz zrobic to jednolinijkowo bez uzycia petli, etc. (oraz oczywiście `np.poly1d`). 
Może Ci się przydać metoda `cumprod`.

In [18]:
def poly(a= np.arange(1,10), x=0):
    vals=np.ones(len(a))
    vals[1:] = x
    vals = np.cumprod(vals) 
    return a@vals
poly()
def poly2(a= np.arange(1,10),x = 1):
    return a @ np.power(x, np.arange(len(a)))
poly2()

np.int64(45)


## Obrazki

Do wyświetlania obrazków w notebooku potrzebny będzie `matplotlib`. W PyCharmie można użyć `imshow` z biblioteki `scipy`.

In [120]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [121]:
img = mpimg.imread('images/doggo.png')
plt.imshow(img);

FileNotFoundError: [Errno 2] No such file or directory: 'images/doggo.png'

### Zad 9.

Napisz funckje do przetwarzania obrazu do skali szarości wg wzoru:

$$ 0.2126 \times R + 0.7152 \times  G + 0.0722 \times B $$

### Zadanie 10.

Wyłącznie za pomocą metod numpy napisz kod do interpolacji liniowej pomiędzy parą punktów (dowolnej wymiarowości) wg wzoru:

$$ x_i = \lambda x_1 + (1 - \lambda) x_2$$

Kod powinien od razu generować interpolacje dla wielu wartości $\lambda$, np dla 10 różnych $\lambda \in \{0, 0.1, 0.2, \dots, 1\}$